server:
  port: 9001
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mytest-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      topic: exampletopic
